# Site settings
title: Koos Kleven
email: koos42+blogs@gmail.com
description: >
  Koos Kleven is a software engineer and artist in Seattle, WA. This is his
  homepage and a generally good launch point to find other information about him.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: koos42
github_username:  koos42

# Build settings
markdown: kramdown
